mod config;
mod grpc_client;
mod telemetry;

// The binary uses the library's module instead of compiling its own copy.
use cami_agent::model_runtime;

// Generated by tonic-build. Its client methods return Result<_, tonic::Status>,
// which trips clippy's result_large_err; that code is not ours to change.
#[allow(clippy::result_large_err)]
pub mod proto {
    tonic::include_proto!("cami.device.v1");
}

use anyhow::Result;
use clap::Parser;
use config::Config;
use std::collections::HashSet;
use std::path::PathBuf;
use std::sync::{Arc, Mutex};
use std::time::{Duration, SystemTime, UNIX_EPOCH};
use tokio::sync::watch;
use tokio::task::JoinHandle;
use tokio::time::{interval, sleep};
use tonic::transport::Channel;
use tracing::{error, info, warn};
use tracing_subscriber::EnvFilter;

use proto::{
    agent_service_client::AgentServiceClient, DeploymentAck, DeploymentInstruction, Heartbeat, RegisterRequest,
    WatchRequest,
};

/// Deployment IDs this process has already started. The control plane can send
/// the same instruction more than once (on reconnect, or when a deployment is
/// created while the watch stream is opening); each is executed only once.
type Seen = Arc<Mutex<HashSet<String>>>;

/// Aborts background tasks when dropped, so a reconnect never leaves the old
/// heartbeat and telemetry loops running next to the new ones.
struct AbortOnDrop(Vec<JoinHandle<()>>);

impl Drop for AbortOnDrop {
    fn drop(&mut self) {
        for task in &self.0 {
            task.abort();
        }
    }
}

#[tokio::main]
async fn main() -> Result<()> {
    tracing_subscriber::fmt()
        .with_env_filter(EnvFilter::from_default_env().add_directive("cami_agent=info".parse()?))
        .init();

    let cfg = Config::parse();
    info!(
        device = %cfg.device_name,
        url = %cfg.control_plane_url,
        backend = cfg.resolve_backend().name(),
        "cami agent starting"
    );

    let (model_tx, model_rx) = watch::channel::<Option<model_runtime::ModelHandle>>(None);
    let seen: Seen = Arc::new(Mutex::new(HashSet::new()));

    loop {
        if let Err(e) = run_agent(&cfg, model_tx.clone(), model_rx.clone(), seen.clone()).await {
            error!("agent error: {e:#} — reconnecting in 5s");
        }
        sleep(Duration::from_secs(5)).await;
    }
}

async fn run_agent(
    cfg: &Config,
    model_tx: watch::Sender<Option<model_runtime::ModelHandle>>,
    model_rx: watch::Receiver<Option<model_runtime::ModelHandle>>,
    seen: Seen,
) -> Result<()> {
    // One HTTP/2 channel carries every RPC; clients are cheap clones of it.
    let mut client = grpc_client::connect(&cfg.control_plane_url, &cfg.cert_dir).await?;

    let resp = client
        .register(RegisterRequest {
            device_name: cfg.device_name.clone(),
            labels: cfg.labels(),
            agent_version: env!("CARGO_PKG_VERSION").to_string(),
            arch: std::env::consts::ARCH.to_string(),
            os: std::env::consts::OS.to_string(),
        })
        .await?;
    let device_id = resp.into_inner().device_id;
    info!(%device_id, "registered with control plane");

    let telemetry_task = tokio::spawn(telemetry::run_telemetry_loop(
        client.clone(),
        device_id.clone(),
        model_rx,
        Duration::from_secs(cfg.probe_interval_secs.max(1)),
    ));
    let heartbeat_task = tokio::spawn(heartbeat_loop(client.clone(), device_id.clone()));
    let _background = AbortOnDrop(vec![telemetry_task, heartbeat_task]);

    // Blocks until the stream ends or errors; dropping `_background` then
    // stops the heartbeat and telemetry tasks before main reconnects.
    watch_deployments(&mut client, &device_id, model_tx, cfg, &seen).await
}

async fn heartbeat_loop(mut client: AgentServiceClient<Channel>, device_id: String) {
    let mut ticker = interval(Duration::from_secs(10));
    loop {
        ticker.tick().await;
        if let Err(e) = client
            .send_heartbeat(Heartbeat {
                device_id: device_id.clone(),
                ts_unix: unix_now(),
            })
            .await
        {
            warn!("heartbeat failed: {e}");
        }
    }
}

async fn watch_deployments(
    client: &mut AgentServiceClient<Channel>,
    device_id: &str,
    model_tx: watch::Sender<Option<model_runtime::ModelHandle>>,
    cfg: &Config,
    seen: &Seen,
) -> Result<()> {
    info!(%device_id, "watching for deployments");

    let mut stream = client
        .watch_deployments(WatchRequest {
            device_id: device_id.to_string(),
        })
        .await?
        .into_inner();

    while let Some(instr) = stream.message().await? {
        let first_time = seen
            .lock()
            .map(|mut s| s.insert(instr.deployment_id.clone()))
            .unwrap_or(true);
        if !first_time {
            info!(deployment_id = %instr.deployment_id, "already handling this deployment; ignoring repeat");
            continue;
        }
        info!(
            deployment_id = %instr.deployment_id,
            model_id = %instr.model_id,
            "received deployment instruction"
        );

        tokio::spawn(execute_deployment(
            client.clone(),
            device_id.to_string(),
            instr,
            model_tx.clone(),
            cfg.clone(),
        ));
    }
    Ok(())
}

async fn execute_deployment(
    client: AgentServiceClient<Channel>,
    device_id: String,
    instr: DeploymentInstruction,
    model_tx: watch::Sender<Option<model_runtime::ModelHandle>>,
    cfg: Config,
) {
    let model_id = instr.model_id.as_str();
    let cache_dir = PathBuf::from(&cfg.model_cache_dir);
    let report =
        |status: &'static str, error_msg: String| ack(&client, &device_id, &instr.deployment_id, status, error_msg);

    report("downloading", String::new()).await;
    let fetched =
        match model_runtime::download_artifact(model_id, &instr.artifact_url, &instr.artifact_sha256, &cache_dir).await
        {
            Ok(f) => f,
            Err(e) => {
                error!(%model_id, "download failed: {e:#}");
                report("failed", format!("{e:#}")).await;
                return;
            }
        };

    report("verifying", String::new()).await;
    let artifact = match model_runtime::verify_fetched(model_id, fetched, &instr.artifact_sha256, &cache_dir).await {
        Ok(path) => path,
        Err(e) => {
            error!(%model_id, "verification failed: {e:#}");
            report("failed", format!("{e:#}")).await;
            return;
        }
    };

    let backend = cfg.resolve_backend();
    info!(%model_id, backend = backend.name(), path = %artifact.display(), "loading verified artifact");

    match model_runtime::load_model(model_id, &artifact, backend).await {
        Ok(handle) => {
            let mode = handle.backend.name();
            model_tx.send_replace(Some(handle));
            report("running", String::new()).await;
            info!(%model_id, %mode, "model running");
        }
        Err(e) => {
            error!(%model_id, "model load failed: {e:#}");
            report("failed", format!("{e:#}")).await;
        }
    }
}

/// Reports deployment progress, retrying a few times: a lost "running" or
/// "failed" would otherwise leave the control plane's view stuck.
async fn ack(
    client: &AgentServiceClient<Channel>,
    device_id: &str,
    deployment_id: &str,
    status: &str,
    error_msg: String,
) {
    for attempt in 1u64..=3 {
        let mut c = client.clone();
        let result = c
            .ack_deployment(DeploymentAck {
                deployment_id: deployment_id.to_string(),
                device_id: device_id.to_string(),
                status: status.to_string(),
                error_msg: error_msg.clone(),
            })
            .await;
        match result {
            Ok(_) => return,
            Err(e) => {
                warn!(%deployment_id, %status, attempt, "ack failed: {e}");
                sleep(Duration::from_secs(2 * attempt)).await;
            }
        }
    }
    error!(%deployment_id, %status, "giving up on ack after 3 attempts");
}

fn unix_now() -> i64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs() as i64
}
